<?php 
if(!empty($class)){
    $class = $class ;
}else{
    $class = "";
}

 ?>

<!DOCTYPE html>
<html class="<?= $class; ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <div class="res1">
        <div style="margin-left: 2%;" class="res2">
        <i class="fab fa-facebook" style="color: white;font-size: 23px; margin-right: 9px;"></i>
        <i class="fas fa-envelope" style="color: white;font-size: 23px;margin-right: 9px;"></i>
        <i class="fab fa-twitter-square" style="color: white;font-size: 23px;margin-right: 9px;"></i>
        </div>
         <div style="margin-top:3px;position: absolute;left:82%;" class="res">
            <i class="fas fa-shopping-cart" style="color:white; float:right;"></i>
        <span style="color:white; float:right; margin-right: 20px;">Télé : +212706143598</span>
    </div>
        
       
    </div>
    <nav>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/nvimg/logofood.png" height="63" width="57" alt="3WA Restaurant"><span style="position: relative;top: 9px;">Restaurant</span> 
        </a>
    </h1>
    <div style="position: relative;top: 16px;left: 184px;">
        
        <?php $user = new UserSession();
        if(!$user->verifysession()){
         ?>
        
        <a href="<?= $requestUrl; ?>/user/inscription" style="margin: 14px;border: solid 1px;padding: 9px;border-radius: 10%;font-weight: 500;" class="user">inscription</a>
            <a href="<?= $requestUrl; ?>/user/login" style="margin: 14px;border: solid 1px;padding: 9px;border-radius: 10%;font-weight: 500;" class="user">Connexion</a>

        <?php }else{ ?>
        <div class="hover" onclick="add()">
            <i class="fas fa-user"></i>
        </div>
            <div class="dropdown-menu" id="click">
    <a class="dropdown-item" href="<?= $requestUrl; ?>/panier">
        <span>
        <i class="fas fa-user-circle" style="position: relative;left: -12px;top: 3px;font-size:19px;color: black;"></i>
                
                <?php
                $email = $_SESSION['email']; 
                $meal = new MealModel();
                $name = $meal->fetch($email);
                 echo $name['name']; ?>
            
            </span>
        </a>
                <a class="dropdown-item" href="<?= $requestUrl; ?>/panier"><i class="fas fa-shopping-cart" style="position: relative;left: -12px;"></i>mon commend</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<?= $requestUrl ?>/user/logout" style="text-align: center;font-size: 20px;color: red;">déconnect</a>
        </div>
            </div>

        <?php } ?>
</div>
    </nav>
    <div class="background_header">
        <h1 class="titre-background">Restaurant America!</h1>
    </div>
</header>

<!-- Interface utilisateur -->
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
    </ul>



<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
   <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>